name: Automatic Revert

on:
  issue_comment:
    types: [created]

jobs:
  revert-commit:

    runs-on: ubuntu-latest

    if: contains(github.event.comment.body, '/revert')

    steps:
      - uses: actions/checkout@v1
      - name: Automatic Revert
        uses: sandesh2026/revert@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
